### PR TITLE
Added uws for Node.js

### PR DESCRIPTION
**Pull request by iONinja**
Hey! µWebSockets is also available for Node.js, so I have added it there.

### CODE REVIEW

**Comment by facundofarias** [comment]
Hello @iONinja! Thanks for the contribution!
Can you please use the repository URL (https://github.com/uNetworking/uWebSockets) instead of the NPM one?
Cheers!

**Comment by iONinja** [comment]
Hi @facundofarias,
Thanks! :slight_smile:
The only problem with linking the repository is that it's only C++ with no mention of the Node.js version.
Any ideas?

**Comment by facundofarias** [comment]
Got it @iONinja!
Let's use the NPM, no problem.
Thanks!

**Comment by iONinja** [comment]
No problem, @facundofarias

**Pull request merged**
